version: "3.8"
services:
    db:
        image: postgres:16
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB:-postgres}
        networks:
            - tha-test
        ports:
            - "${POSTGRES_PORT:-5432}:5432"


    provisioner:
        build:
            context:
                test_provisioner
        depends_on:
            - db
        restart: "no"
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${THA_DB_URI}
            - THA_TEST_PASSWORD=${THA_TEST_PASSWORD}

networks:
    tha-test:

volumes:
    prometheus_data:
    grafana_data:
