version: "3.8"
services:
    db:
        image: postgres:16
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
        networks:
            - tha-test
        ports:
            - 5432:5432

    prometheus:
        image: prom/prometheus:latest
        restart: always
        networks:
            - tha-test
        ports:
            - "9090:9090"
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus
        command:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --storage.tsdb.retention.time=200h
            - --web.enable-lifecycle

    grafana:
        image: grafana/grafana:latest
        restart: always
        networks:
            - tha-test
        ports:
            - "4000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        volumes:
            - grafana_data:/var/lib/grafana
            - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
            - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards

    postgres_exporter:
        image: prometheuscommunity/postgres-exporter:latest
        restart: always
        networks:
            - tha-test
        ports:
            - "9187:9187"
        environment:
            - DATA_SOURCE_NAME=postgresql://josh@host.docker.internal:5432/prod_replica?sslmode=disable
        extra_hosts:
            - "host.docker.internal:host-gateway"

    provisioner:
        build:
            context:
                test_provisioner
        depends_on:
            - db
        restart: "no"
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${THA_DB_URI}
            - THA_TEST_PASSWORD=${THA_TEST_PASSWORD}

networks:
    tha-test:

volumes:
    prometheus_data:
    grafana_data:
