version: "3"
services:
    broker:
        image: "rabbitmq:3-management"
        restart: always
        networks:
            - tha-connect
        ports:
            - ${BROKER_PORT}
            - ${BROKER_ADMIN_PORT}
    api:
        image: ilriccio/thehistoryatlas:api-dev
        restart: always
        depends_on:
            - broker
            - writemodel
            - readmodel
            - eventstore
        build: ./api
        ports:
            - "4000:4000"
        networks:
            - tha-connect

    readmodel:
        image: ilriccio/thehistoryatlas:readmodel-dev
        restart: always
        depends_on:
            - db
            - broker
            - history
            - provisioner
        build:
            context: ./readmodel
        environment:
            - PROD_DB_URI=${READMODEL_CONN_STR}
            - DEV_DB_URI=${READMODEL_CONN_STR_DEV}
            - TESTING=${TESTING}
            - CONFIG=${CONFIG}
        networks:
            - tha-connect

    writemodel:
        image: ilriccio/thehistoryatlas:writemodel-dev
        restart: always
        depends_on:
            - db
            - broker
            - history
            - eventstore
            - provisioner
        build:
            context: ./writemodel
        networks:
            - tha-connect
        environment:
            - PROD_DB_URI=${WRITEMODEL_CONN_STR}
            - DEV_DB_URI=${WRITEMODEL_CONN_STR_DEV}
            - CONFIG=${CONFIG}
            - TESTING=${TESTING}

    eventstore:
        image: ilriccio/thehistoryatlas:eventstore-dev
        restart: always
        depends_on:
            - broker
            - db
            - provisioner
        build:
            context: ./eventstore
        networks:
            - tha-connect
        environment:
            - PROD_DB_URI=${EVENTSTORE_CONN_STR}
            - DEV_DB_URI=${EVENTSTORE_CONN_STR_DEV}
            - CONFIG=${CONFIG}
            - TESTING=${TESTING}

    history:
        image: ilriccio/thehistoryatlas:history-dev
        restart: always
        depends_on: 
            - broker
            - db
            - provisioner
        build:
            context: ./history
        networks:
            - tha-connect
        environment:
            - PROD_DB_URI=${EVENTSTORE_CONN_STR}
            - DEV_DB_URI=${EVENTSTORE_CONN_STR_DEV}
            - CONFIG=${CONFIG}
            - TESTING=${TESTING}

    nlp:
        image: ilriccio/thehistoryatlas:nlp-dev
        restart: always
        depends_on: 
            - broker
            - db
            - provisioner
        build:
            context: ./nlp
        environment: 
            - PROD_DB_URI=${NLP_CONN_STR}
            - DEV_DB_URI=${NLP_CONN_STR_DEV}
            - CONFIG=${CONFIG}
            - TESTING=${TESTING}

        networks:
            - tha-connect

    geo:
        image: ilriccio/thehistoryatlas:geo-dev
        restart: always
        depends_on: 
            - db
            - broker
            - provisioner
        build:
            context: ./geo
        environment:
            - PROD_DB_URI=${GEO_CONN_STR}
            - DEV_DB_URI=${GEO_CONN_STR_DEV}
            - TESTING=${TESTING}
            # choose between one of the following two city lists:
            # cities500 is much more comprehensive, and also requires a much longer build.
            - GEONAMES_URL=https://download.geonames.org/export/dump/cities15000.zip
            # - GEONAMES_URL=https://download.geonames.org/export/dump/cities500.zip
            - CONFIG=${CONFIG}

        networks: 
            - tha-connect

    accounts:
        image: ilriccio/thehistoryatlas:accounts-dev
        restart: always
        depends_on:
            - broker
            - db
            - provisioner
        build:
            context: ./accounts
        environment:
            - PROD_DB_URI=${ACCOUNTS_CONN_STR}
            - DEV_DB_URI=${ACCOUNTS_CONN_STR_DEV}
            - SEC_KEY=${ACCOUNTS_SEC_KEY}
            - TTL=${ACCOUNTS_TTL}
            - TESTING=${TESTING}
            - REFRESH_BY=${ACCOUNTS_REFRESH_BY}
            - CONFIG=${CONFIG}

        networks:
            - tha-connect

    db:

        # NOTE: using postgres 13.3 to avoid m1 libpq issue:
        #       https://github.com/psycopg/psycopg2/issues/1360#issuecomment-1209943490
        image: postgres:13.3
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
        networks:
            - tha-connect
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data

    provisioner:
        build:
            context:
                ./provisioner
        depends_on:
            - db
        restart: "no"
        networks:
            - tha-connect
        environment:
            - EVENTSTORE_SERVICE_PASSWORD=${EVENTSTORE_SERVICE_PASSWORD}
            - READMODEL_SERVICE_PASSWORD=${READMODEL_SERVICE_PASSWORD}
            - WRITEMODEL_SERVICE_PASSWORD=${WRITEMODEL_SERVICE_PASSWORD}
            - ACCOUNTS_SERVICE_PASSWORD=${ACCOUNTS_SERVICE_PASSWORD}
            - GEO_SERVICE_PASSWORD=${GEO_SERVICE_PASSWORD}
            - NLP_SERVICE_PASSWORD=${NLP_SERVICE_PASSWORD}
            - THA_DB_URI=${THA_DB_URI}
volumes:
    db:
networks:
    tha-connect:
