version: "3.9"
services:
    broker:
        image: "rabbitmq:3-management"
        networks:
            - tha-connect
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - broker:/var/lib/rabbitmq
    mongodb:
        image: "mongo"
        networks:
            - tha-connect
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
    api:
        depends_on:
            - broker
        build: ./api
        ports:
            - "4000:4000"
        networks:
            - tha-connect
    readmodel:
        depends_on:
            - broker
            - mongodb
        build: ./readmodel
        networks:
            - tha-connect
volumes:
    broker:
    mongodata:
networks:
    tha-connect:
