version: "3.9"
services:
    broker:
        image: "rabbitmq:3-management"
        networks:
            - tha-connect
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - broker:/var/lib/rabbitmq
    api:
        depends_on:
            - broker
            - writemodel
            - readmodel
            - eventstore
        build: ./api
        ports:
            - "4000:4000"
        networks:
            - tha-connect
    readmodel:
        depends_on:
            - broker
            - history
        build:
            context: ./readmodel
            args:
                test: "True"
        networks:
            - tha-connect
    writemodel:
        depends_on:
            - broker
            - history
            - eventstore
        build: 
            context: ./writemodel
            args:
                test: "True"
        networks:
            - tha-connect
    eventstore:
        depends_on:
            - broker
        build:
            context: ./eventstore
            args:
                test: "False"
        networks:
            - tha-connect
        volumes:
            - teststore:/data/db
    history:
        depends_on: 
            - broker
        build:
            context: ./history
            args:
                test: "False"
        networks: 
            - tha-connect
        volumes:
            - teststore:/data/db
volumes:
    broker:
    teststore:
networks:
    tha-connect:
