version: "3"

services:

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - tha-test
    ports:
      - 5432:5432

  readmodel:
    build:
      context:
        ./readmodel
    command: ["python3", "-m", "pytest", "-vvv"]
    networks:
      - tha-test
    environment:
      - TEST_DB_URI=${TEST_DB_URI}
      - REQUIREMENT_FILE=test-requirements.txt

networks:
    tha-test:
