version: "3"
services:
    db:
        # NOTE: using postgres 13.3 to avoid m1 libpq issue:
        #       https://github.com/psycopg/psycopg2/issues/1360#issuecomment-1209943490
        image: postgres:16
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
        networks:
            - tha-test
        ports:
            - 5432:5432

    provisioner:
        build:
            context:
                test_provisioner
        depends_on:
            - db
        restart: "no"
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${THA_DB_URI}
            - THA_TEST_PASSWORD=${POSTGRES_PASS}

    server:
        image: ilriccio/thehistoryatlas:test_server
        command: [ "python3", "-m", "pytest", "-vvv" ]
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${TEST_USER_DB_URI}
            - TTL=${TTL}
            - REFRESH_BY=${REFRESH_BY}
            - SEC_KEY=${SEC_KEY}
networks:
    tha-test:
