version: "3"
services:
    db:
        image: postgres:16
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
        networks:
            - tha-test
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

    provisioner:
        build:
            context:
                test_provisioner
        depends_on:
            db:
                condition: service_healthy
        restart: "no"
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${THA_DB_URI}
            - THA_TEST_PASSWORD=${POSTGRES_PASS}
            
    migrations:
        image: ilriccio/thehistoryatlas:test_server
        command: ["python", "-m", "the_history_atlas.scripts.run_migrations"]
        depends_on:
            provisioner:
                condition: service_completed_successfully
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${THA_DB_URI}

    server:
        image: ilriccio/thehistoryatlas:test_server
        command: [ "python3", "-m", "pytest", "-vvv" ]
        depends_on:
            migrations:
                condition: service_completed_successfully
        networks:
            - tha-test
        environment:
            - THA_DB_URI=${THA_DB_URI}
            - TTL=${TTL}
            - REFRESH_BY=${REFRESH_BY}
            - SEC_KEY=${SEC_KEY}
networks:
    tha-test:
