apiVersion: v1
items:


  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
      name: adminer
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: adminer
    status:
      loadBalancer: {}


  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api
      name: api
    spec:
      type: LoadBalancer
      ports:
        - name: "4000"
          port: 4000
          targetPort: 4000
      selector:
        io.kompose.service: api
    status:
      loadBalancer: {}


  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: broker
      name: broker
    spec:
      ports:
        - name: "5672"
          port: 5672
          targetPort: 5672
        - name: "15672"
          port: 15672
          targetPort: 15672
      selector:
        io.kompose.service: broker
    status:
      loadBalancer: {}


  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "5432"
          port: 5432
          targetPort: 5432
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: accounts
      name: accounts
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: accounts
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: accounts
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: ACCOUNTS_CONN_STR
                - name: REFRESH_BY
                  value: "7200"
                - name: SEC_KEY
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: SEC_KEY
                - name: TTL
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: TTL
              image: ilriccio/thehistoryatlas:accounts-dev
              name: accounts
              resources: {}
          restartPolicy: Always
    status: {}


  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: tha-connect
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/tha-connect: "true"
      podSelector:
        matchLabels:
          io.kompose.network/tha-connect: "true"


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
      name: adminer
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: adminer
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: adminer
        spec:
          containers:
            - image: adminer
              name: adminer
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api
      name: api
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: api
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: api
        spec:
          containers:
            - image: ilriccio/thehistoryatlas:api-dev
              name: api
              ports:
                - containerPort: 4000
              resources: {}
          restartPolicy: Always
    status: {}


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: broker
      name: broker
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: broker
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: broker
        spec:
          containers:
            - image: rabbitmq:3-management
              name: broker
              ports:
                - containerPort: 5672
                - containerPort: 15672
              resources: {}
          restartPolicy: Always
    status: {}


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: db
        spec:
          containers:
            - env:
                - name: PGDATA
                  value: /var/lib/postgresql/data/pgdata
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: POSTGRES_USER
              image: postgres
              name: db
              ports:
                - containerPort: 5432
              resources: {}
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: db
          restartPolicy: Always
          volumes:
            - name: db
              persistentVolumeClaim:
                claimName: db
    status: {}


  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    status: {}


  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: eventstore
      name: eventstore
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: eventstore
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: eventstore
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: EVENTSTORE_CONN_STR
              image: ilriccio/thehistoryatlas:eventstore-dev
              name: eventstore
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: geo
      name: geo
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: geo
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: geo
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: GEONAMES_URL
                  value: https://download.geonames.org/export/dump/cities500.zip
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: GEO_CONN_STR
              image: ilriccio/thehistoryatlas:geo-dev
              name: geo
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: history
      name: history
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: history
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: history
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: EVENTSTORE_CONN_STR
              image: ilriccio/thehistoryatlas:history-dev
              name: history
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nlp
      name: nlp
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: nlp
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: nlp
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: NLP_CONN_STR
                - name: TESTING
                  value: "False"
              image: ilriccio/thehistoryatlas:nlp-dev
              name: nlp
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: readmodel
      name: readmodel
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: readmodel
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: readmodel
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: READMODEL_CONN_STR
              image: ilriccio/thehistoryatlas:readmodel-dev
              name: readmodel
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o tha-config.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: writemodel
      name: writemodel
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: writemodel
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o tha-config.yaml
            kompose.version: 1.26.1 (HEAD)
          creationTimestamp: null
          labels:
            io.kompose.network/tha-connect: "true"
            io.kompose.service: writemodel
        spec:
          containers:
            - env:
                - name: CONFIG
                  value: DEVELOPMENT
                - name: DEV_DB_URI
                  valueFrom:
                    secretKeyRef:
                      name: tha-secret
                      key: WRITEMODEL_CONN_STR
              image: ilriccio/thehistoryatlas:writemodel-dev
              name: writemodel
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

