
federation_version: 2
subgraphs:
  api:
    routing_url: http://localhost:4000/
    schema:
      subgraph_url: http://localhost:4000/

  writemodel:
    routing_url: http://localhost:8800/
    schema:
      subgraph_url: http://localhost:8800/

  readmodel:
    routing_url: http://localhost:8801/
    schema:
      subgraph_url: http://localhost:8801/
