from .person_was_born import PersonWasBorn
from .person_died import PersonDied
from .person_education_began import PersonEducationBegan
from .person_education_ended import PersonEducationEnded
from .person_started_working_for import PersonStartedWorkingFor
from .person_stopped_working_for import PersonStoppedWorkingFor
from .person_received_academic_degree import PersonReceivedAcademicDegree
