global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics

  - job_name: 'postgresql'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres_exporter:9187']
