"""add tag_instances.after

Revision ID: a68f7c2c57d9
Revises: 2024041501
Create Date: 2025-04-16 14:17:33.001637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a68f7c2c57d9"
down_revision: Union[str, None] = "2024041501"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tag_instances",
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag_instances", "after")
    # ### end Alembic commands ###
