
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ReadModel"
version = "0.0.1"
requires-python = ">=3.9"
dependencies = [
    'importlib-metadata; python_version<"3.8"',
    "sqlalchemy",
    "psycopg2-binary",
    "black",
    "pytest"
]


