
GRANT CONNECT ON DATABASE eventstore TO readwrite_eventstore;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite_eventstore;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite_eventstore;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite_eventstore;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite_eventstore;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite_eventstore;
ALTER DATABASE eventstore SET timezone TO 'UTC';
GRANT readwrite_eventstore TO eventstore_service;

GRANT CONNECT ON DATABASE readmodel TO readwrite_readmodel;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite_readmodel;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite_readmodel;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite_readmodel;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite_readmodel;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite_readmodel;
ALTER DATABASE readmodel SET timezone TO 'UTC';
GRANT readwrite_readmodel TO readmodel_service;

GRANT CONNECT ON DATABASE writemodel TO readwrite_writemodel;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite_writemodel;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite_writemodel;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite_writemodel;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite_writemodel;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite_writemodel;
ALTER DATABASE writemodel SET timezone TO 'UTC';
GRANT readwrite_writemodel TO writemodel_service;

GRANT CONNECT ON DATABASE accounts TO readwrite_accounts;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite_accounts;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite_accounts;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite_accounts;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite_accounts;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite_accounts;
ALTER DATABASE accounts SET timezone TO 'UTC';
GRANT readwrite_accounts TO accounts_service;

GRANT CONNECT ON DATABASE geo TO readwrite_geo;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite_geo;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite_geo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite_geo;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite_geo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite_geo;
ALTER DATABASE geo SET timezone TO 'UTC';
GRANT readwrite_geo TO geo_service;

GRANT CONNECT ON DATABASE nlp TO readwrite_nlp;
GRANT USAGE, CREATE ON SCHEMA public TO readwrite_nlp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO readwrite_nlp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite_nlp;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO readwrite_nlp;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO readwrite_nlp;
ALTER DATABASE nlp SET timezone TO 'UTC';
GRANT readwrite_nlp TO nlp_service;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE eventstore FROM PUBLIC;
REVOKE ALL ON DATABASE writemodel FROM PUBLIC;
REVOKE ALL ON DATABASE readmodel FROM PUBLIC;
REVOKE ALL ON DATABASE accounts FROM PUBLIC;
REVOKE ALL ON DATABASE geo FROM PUBLIC;
REVOKE ALL ON DATABASE nlp FROM PUBLIC;
