name: "Test Services"

on:
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Test Environment
        env:
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
        run: docker compose -f tests.yaml up db -d

      - name: Test WriteModel
        env:
          TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
        run: |
          docker compose -f tests.yaml up --build writemodel --exit-code-from writemodel

      - name: Test EventStore
        env:
          TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
        run: |
          docker compose -f tests.yaml up --build eventstore --exit-code-from eventstore

      - name: Test ReadModel
        env:
          TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
        run: |
          docker compose -f tests.yaml up --build readmodel --exit-code-from readmodel
