name: Writemodel Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request: # test action configuration
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    -
      name: Build and push amd64
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./writemodel
        build-contexts: |
          pylib=./pylib
          testlib=./testlib
        platforms: linux/amd64, linux/arm64
        file: ./writemodel/Dockerfile
        push: true
        tags: ilriccio/thehistoryatlas:writemodel-${{ github.sha }}

    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
