name: Readmodel Dev Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: /readmodel
        platforms: linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: ilriccio/thehistoryatlas:readmodel-dev
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
