name: "Test Services"

on:
  pull_request:
    branches:
      - main

jobs:

  Test-Server:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v3
      -   name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
      -   name: Build and export
          uses: docker/build-push-action@v2
          with:
            context: ./server
            file: ./server/Dockerfile
            tags: ilriccio/thehistoryatlas:test_server
            load: true
      -   name: Setup Test Environment
          env:
            POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          run: docker compose -f test_cluster.yaml up db provisioner -d
      -   name: Test Server
          env:
            THA_DB_URI: ${{ secrets.THA_DB_URI }}
            TTL: ${{ secrets.ACCOUNTS_TTL }}
            REFRESH_BY: ${{ secrets.ACCOUNTS_REFRESH_BY }}
            SEC_KEY: ${{ secrets.ACCOUNTS_SEC_KEY }}
          run: |
            docker compose -f test_cluster.yaml up server --exit-code-from server
